MVVM_project/Pages/Circle/Addtocircle.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MongoDB.Driver;
using DAB_NoSQL_assignment.Models;
using Microsoft.AspNetCore.Mvc.Internal;
using Microsoft.Extensions.Configuration;

namespace DAB_NoSQL_assignment
{
    public class AddtocircleModel : PageModel
    {
        private readonly IMongoCollection<User> _users;
        private readonly IMongoCollection<Circle> _circles;

        public AddtocircleModel(IConfiguration config)
        {
            var client = new MongoClient("mongodb://localhost:27017");
            var database = client.GetDatabase("DAB_AFL3_Db");
            _users = database.GetCollection<User>("Users");
            _circles = database.GetCollection<Circle>("CircleIDs");
        }
        public List<User> UserList { get; set; }
        [BindProperty]
        public string MbrName { get; set; }

        [BindProperty]
        public string activecircle { get; set; }

        public List<Circle> circleList;

        public void OnGet()
        {
            UserList = _users.Find(user => true).ToList();
            circleList = _circles.Find(circle => true).ToList();
        }

        public string getmbrname(string id)
        {
            User mbr = _users.Find(u => u.Id == id).FirstOrDefault();
            if (mbr == null)
            {
                return "placeholder";
            }
            return mbr.Name;
        }

        public IActionResult OnPostAddMember(string id)
        {
            if (MbrName == null)
            {
                return RedirectToPage();
            }

            User membertoadd = _users.Find(u => u.Name == MbrName).FirstOrDefault();
            Circle circletoaddmember = _circles.Find(c => c.Id == id).FirstOrDefault();

            if (circletoaddmember.Members == null)
            {
                circletoaddmember.Members = new List<string>();
            }
            circletoaddmember.Members.Add(membertoadd.Id);

            _circles.FindOneAndReplace(c => c.Id == circletoaddmember.Id,circletoaddmember);

            if (membertoadd.CircleIDs == null)
            {
                membertoadd.CircleIDs = new List<string>();
            }
            membertoadd.CircleIDs.Add(circletoaddmember.Id);

            _users.FindOneAndReplace(user => user.Name == MbrName, membertoadd);

            return RedirectToPage();
        }
    }
}

MVVM_project/Pages/Circle/createcircle.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MongoDB.Driver;
using DAB_NoSQL_assignment.Models;
using Microsoft.Extensions.Configuration;

namespace DAB_NoSQL_assignment
{
    public class createcircleModel : PageModel
    {
        private readonly IMongoCollection<User> _users;
        private readonly IMongoCollection<Circle> _circles;
        private User user;
        public List<User> UserList { get; set; }
        public createcircleModel(IConfiguration config)
        {
            var client = new MongoClient("mongodb://localhost:27017");
            var database = client.GetDatabase("DAB_AFL3_Db");
            _users = database.GetCollection<User>("Users");
            _circles = database.GetCollection<Circle>("CircleIDs");
        }

        [BindProperty]
        public Circle circlebindproperty { get; set; }

        public void OnGet()
        {
            //Load list of User
            UserList = _users.Find(user => true).ToList();
        }

        [BindProperty]
        public String owner { get; set; }

        public IActionResult OnPost()
        {
            UserList = _users.Find(user => true).ToList();
            user = _users.Find(user => user.Name == owner).FirstOrDefault();

            if (user == null)
            {
                return Page();
            }
            circlebindproperty.ForUser = user.Name;
            circlebindproperty.Members = new List<string>();
            _circles.InsertOne(circlebindproperty);

            if (user.CircleIDs == null)
            {
                user.CircleIDs = new List<string>();
            }

            user.CircleIDs.Add(circlebindproperty.Id);
            _users.FindOneAndReplace(u => u.Name == user.Name, user);

            return Page();
        }


    }
}

MVVM_project/Pages/Circle/Addtocircle.cshtml
@page
@model DAB_NoSQL_assignment.AddtocircleModel
@{
    ViewData["Title"] = "Add users to circle";
}

<h1>Add users to circle</h1>
<br />
<form method="post">
    <div class="form-group">
        <label asp-for="MbrName">Membername to add</label>
        <input asp-for="MbrName" class="form-control" />
        <span asp-validation-for="MbrName" class="text-danger"></span>
    </div>
    <div class="row">
        <div class="col-md-6">

            @if (Model.circleList != null)
            {

                @foreach (var circle in @Model.circleList)
                {
                    <table>
                        <tr>
                            <th>Circle Id</th>
                            <th>Circle Owner</th>
                        </tr>
                        <tr>
                            <td>@circle.Id</td>
                            <td>@Model.UserList.Find(user => user.Id == circle.ForUser).Name</td>
                        </tr>
                        <tr>
                            <th>Members: </th>
                            <th>
                                Add member:
                                <button type="submit" class="btn btn-primary" asp-page-handler="AddMember"
                                        asp-route-id="@circle.Id">
                                    Add
                                </button>

                            </th>
                        </tr>
                        @if (circle.Members != null)
                        {
                            @foreach (var member in circle.Members)
                            {
                                <tr>
                                    <td>@member</td>
                                    <td>@Model.getmbrname(member)</td>
                                </tr>
                            }
                        }
                    </table>
                    <br />
                    <br />
                }


            }

    </div>
</div>
</form>

MVVM_project/Pages/Circle/createcircle.cshtml
@page
@model DAB_NoSQL_assignment.createcircleModel
@{
    ViewData["Title"] = "create circle";
}

<h1>Create a Circle</h1>
<br />
<div class="row">
    <div class="col-md-6">
        <form method="post">
            <hr />
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="owner">User name (owner of circle)</label>
                <input asp-for="owner" class="form-control" placeholder="ex. Jim" />
                <span asp-validation-for="owner" class="text-danger"></span>
            </div>
            <hr />
            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </div>
</div>